const swaggerUi = require("swagger-ui-express");
const swaggerJsDoc = require("swagger-jsdoc");

const options = {
  swaggerDefinition: {
    info: {
      title: "Swagger Documentation",
      version: "0.1",
      description: "API documentation generated by Swagger",
    },
    securitySchemes: {
      BasicAuth: "global",
      ApiKeyAuth: {
        type: "apiKey",
        in: "header",
        name: "Authorization",
      },
    },
    basePath: "/",
  },
  apis: ["./src/controller/**/*.js"],
};

module.exports = (app) => {
  app.use("/swagger", swaggerUi.serve, swaggerUi.setup(swaggerJsDoc(options)));
};
